# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [10]:
array1d_1 = np.zeros(10)
array1d_1[4] = 1
print(f'1D array:\n{array1d_1}')
array2d_1 = array1d_1.reshape(5,2)
print(f'2D array:\n{array2d_1}')

1D array:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
2D array:
[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [12]:
array1d_2 = np.flip(np.arange(10, 50, 1))
print(f'Array:\n{array1d_2}')
even = array1d_2[array1d_2 % 2 == 0]
print(f'Filtered array with even numbers:\n{even}')

Array:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Filtered array with even numbers:
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [20]:
array2d_2 = np.arange(0, 9, 1).reshape(3, 3)
print(array2d_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [22]:
array3d = np.random.randn(4, 3, 2)
print(f'Array:\n{array3d}')
print(f'Min: {np.min(array3d)}; Max: {np.max(array3d)}')

Array:
[[[ 0.16086118 -0.85751279]
  [-0.63190052 -0.88938782]
  [-0.14939328  0.96072176]]

 [[ 0.11912147  0.66249056]
  [ 0.84345395 -0.8102551 ]
  [ 0.40533002  2.32115011]]

 [[ 0.19358059 -0.09024338]
  [ 0.66991657 -0.90442534]
  [ 1.59632625 -1.37433628]]

 [[-0.57057511 -1.19331274]
  [-0.37772308 -0.46137189]
  [-0.24372551 -0.55997722]]]
Min: -1.374336284574419; Max: 2.321150107693364


In [31]:
for i, j in zip(range(7), range(4)):
    print(i, j)

0 0
1 1
2 2
3 3


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [47]:
matrix1 = np.random.randint(10, size=(6, 4))
matrix2 = np.random.randint(5, size=(4, 3))
# Easy way
result1 = np.matmul(matrix1, matrix2)
# My own functions
def dotproduct(a, b):
    return sum(i*j for i, j in zip(a,b))
def matmul (m1, m2):
    result=np.zeros((m1.shape[0], m2.shape[1]))
    for i in range(result.shape[0]):
        for j in range(result.shape[1]):
            result[i, j] = dotproduct(m1[i,:], m2[:,j])
            # or
            #result[i, j] = np.dot(m1[i, :], m2[:, j])
    return result
result2 = matmul(matrix1, matrix2)
print(f'''A:
{matrix1}
B:
{matrix2}
AxB:
{result1}
{result2}''')

A:
[[9 8 9 9]
 [3 5 3 4]
 [2 8 5 6]
 [7 6 9 3]
 [7 2 4 6]
 [2 4 6 6]]
B:
[[4 0 1]
 [0 4 3]
 [3 0 3]
 [1 3 2]]
AxB:
[[72 59 78]
 [25 32 35]
 [29 50 53]
 [58 33 58]
 [46 26 37]
 [32 34 44]]
[[72. 59. 78.]
 [25. 32. 35.]
 [29. 50. 53.]
 [58. 33. 58.]
 [46. 26. 37.]
 [32. 34. 44.]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [48]:
min, max = -50, 100
array2d = np.random.randint(min, max, size=(7,7))
mean = array2d.mean()
# I am not sure with one to use
# Population standard deviation
std = array2d.std()
# Sample standard deviation
# std = array2d.std(ddof=1)
normalized = (array2d - mean)/std
print(f'''Array:
{array2d}
mean={mean}, std={std}
Normalized:
{normalized}
''')

Array:
[[-14 -31  34  42  69 -37   0]
 [ 13  49  86 -30  46  37  55]
 [ 39  97  24  66  -6   5  16]
 [-20  10  44  36  49 -46  13]
 [-40  -2   1  69   0 -16  -7]
 [-30  11 -42 -26 -33  40 -21]
 [ 59  26   6  14  79  84  85]]
mean=18.428571428571427, std=38.7856485134933
Normalized:
[[-0.83609718 -1.27440363  0.40147398  0.60773584  1.30386961 -1.42910003
  -0.47513893]
 [-0.1399634   0.78821496  1.74217607 -1.2486209   0.71086677  0.47882217
   0.94291136]
 [ 0.53038764  2.02578612  0.14364665  1.22652142 -0.62983532 -0.34622526
  -0.06261521]
 [-0.99079358 -0.2173116   0.6593013   0.45303944  0.78821496 -1.66114462
  -0.1399634 ]
 [-1.50644823 -0.52670439 -0.44935619  1.30386961 -0.47513893 -0.88766265
  -0.65561805]
 [-1.2486209  -0.19152887 -1.55801369 -1.14548997 -1.3259691   0.55617037
  -1.01657631]
 [ 1.04604229  0.19521212 -0.32044253 -0.11418067  1.56169694  1.6906106
   1.71639333]]



# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

### Загрузите датасет Tips из набора датасетов seaborn

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.