# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [2]:
array1d_1 = np.zeros(10)
array1d_1[4] = 1
print(f'1D array:\n{array1d_1}')
array2d_1 = array1d_1.reshape(5,2)
print(f'2D array:\n{array2d_1}')

1D array:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
2D array:
[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [3]:
array1d_2 = np.flip(np.arange(10, 50, 1))
print(f'Array:\n{array1d_2}')
even = array1d_2[array1d_2 % 2 == 0]
print(f'Filtered array with even numbers:\n{even}')

Array:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Filtered array with even numbers:
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [4]:
array2d_2 = np.arange(0, 9, 1).reshape(3, 3)
print(array2d_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [5]:
array3d = np.random.randn(4, 3, 2)
print(f'Array:\n{array3d}')
print(f'Min: {np.min(array3d)}; Max: {np.max(array3d)}')

Array:
[[[ 0.15285778 -0.27956722]
  [-1.02633419 -0.50823347]
  [ 0.08377082 -1.58155178]]

 [[-2.36487683  0.56629279]
  [ 0.7350184  -0.64270674]
  [ 0.82331955  1.93510563]]

 [[ 1.87637036  0.0372722 ]
  [ 1.57969418 -0.15601235]
  [ 0.47012629  1.06641491]]

 [[-0.72180228  1.01090636]
  [ 0.40168851 -1.21607737]
  [ 1.08516767  0.38693185]]]
Min: -2.3648768263994584; Max: 1.9351056335241628


In [6]:
for i, j in zip(range(7), range(4)):
    print(i, j)

0 0
1 1
2 2
3 3


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [7]:
matrix1 = np.random.randint(10, size=(6, 4))
matrix2 = np.random.randint(5, size=(4, 3))
# Easy way
result1 = np.matmul(matrix1, matrix2)
# My own functions
def dotproduct(a, b):
    return sum(i*j for i, j in zip(a,b))
def matmul (m1, m2):
    result=np.zeros((m1.shape[0], m2.shape[1]))
    for i in range(result.shape[0]):
        for j in range(result.shape[1]):
            result[i, j] = dotproduct(m1[i,:], m2[:,j])
            # or
            #result[i, j] = np.dot(m1[i, :], m2[:, j])
    return result
result2 = matmul(matrix1, matrix2)
print(f'''A:
{matrix1}
B:
{matrix2}
AxB:
{result1}
{result2}''')

A:
[[4 1 2 4]
 [8 9 8 0]
 [4 4 2 9]
 [3 1 5 8]
 [8 9 2 2]
 [3 3 6 8]]
B:
[[1 0 4]
 [3 4 0]
 [2 1 0]
 [3 0 4]]
AxB:
[[23  6 32]
 [51 44 32]
 [47 18 52]
 [40  9 44]
 [45 38 40]
 [48 18 44]]
[[23.  6. 32.]
 [51. 44. 32.]
 [47. 18. 52.]
 [40.  9. 44.]
 [45. 38. 40.]
 [48. 18. 44.]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [8]:
min, max = -50, 100
array2d = np.random.randint(min, max, size=(7,7))
mean = array2d.mean()
# I am not sure with one to use
# Population standard deviation
std = array2d.std()
# Sample standard deviation
# std = array2d.std(ddof=1)
normalized = (array2d - mean)/std
print(f'''Array:
{array2d}
mean={mean}, std={std}
Normalized:
{normalized}
''')

Array:
[[ 61 -11 -18  17  81 -22 -14]
 [-48  39 -17  44  58 -22  99]
 [ 90  27 -38  11  80 -30  74]
 [ 90  42  17  32 -48  97  44]
 [ 29 -43  41 -13  28  97 -46]
 [ 73   6  81 -21  55  98  58]
 [ 90  71  89 -32  22 -10 -47]]
mean=27.775510204081634, std=47.74005519097827
Normalized:
[[ 0.69594578 -0.81222173 -0.95884913 -0.22571214  1.1148812  -1.04263621
  -0.87506204]
 [-1.58725225  0.23511682 -0.93790236  0.33985067  0.63310546 -1.04263621
   1.49192307]
 [ 1.30340213 -0.01624443 -1.37778454 -0.35139277  1.09393442 -1.21021038
   0.9682538 ]
 [ 1.30340213  0.29795713 -0.22571214  0.08848942 -1.58725225  1.45002953
   0.33985067]
 [ 0.02564911 -1.4825184   0.27701036 -0.85411527  0.00470234  1.45002953
  -1.54535871]
 [ 0.94730703 -0.45612662  1.1148812  -1.02168944  0.57026515  1.4709763
   0.63310546]
 [ 1.30340213  0.90541349  1.28245536 -1.25210392 -0.12097829 -0.79127496
  -1.56630548]]



# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [20]:
tips = sns.load_dataset('tips')

### Посмотрите на первые 5 строчек

In [11]:
tips.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [12]:
tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [13]:
tips.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

### Посмотрите на распределение числовых признаков

In [14]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Найдите максимальное значение 'total_bill'

In [15]:
tips['total_bill'].max()

50.81

### Найдите количество курящих людей

In [16]:
tips[tips['smoker'] == 'Yes'].size

651

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [17]:
tips.groupby('day')['total_bill'].agg(mean='mean')

mean
day            
Thur  17.682742
Fri   17.151579
Sat   20.441379
Sun   21.410000

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [18]:
tips[tips['total_bill'] > np.median(tips['total_bill'])].groupby('sex')['tip'].agg(mean='mean')

mean
sex             
Male    3.756404
Female  3.663939

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [21]:
print(tips['smoker'].unique())
tips['smoker'] = tips['smoker'].replace(['No', 'Yes'], [0, 1]).astype(np.int8)
print(tips['smoker'].unique())

['No', 'Yes']
Categories (2, object): ['No', 'Yes']
[0 1]


# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.